# Generated by Django 5.2 on 2025-04-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('pan_card', models.CharField(max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('profile', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField(unique=True)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('FIXED', 'Fixed Deposit')], max_length=12)),
                ('branch_name', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date_opened', models.DateField(auto_now_add=True)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.customer')),
            ],
        ),
    ]
